<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class ThreadsTest extends TestCase
{
    use RefreshDatabase;

    protected $thread;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread = factory('App\Thread')->create();
    }

    public function testViewAllThreads()
    {

        $this->get('/threads')->assertSee($this->thread->title);

    }

    public function testReadSingleThread()
    {
        $this->get('/threads/' . $this->thread->id)->assertSee($this->thread->title);
    }

    public function testRepliesAssociatedWithThread()
    {
        $reply = factory('App\Reply')
            ->create(['thread_id' => $this->thread->id]);
        // 那么当我们看 Thread 时
        // 我们也要看到回复
        $this->get('/threads/'.$this->thread->id)
            ->assertSee($reply->body);
    }
    /*
    public function testUserCountTest()
    {
        $count = DB::table('usertest')->select(DB::raw('count(sex = 1 OR NULL) as man,count(sex = 0 OR NULL) as woman'))->first();

        var_dump($count);

        $this->assertNotEmpty($count);
    }
    */
}
